# Generated by Django 2.1.1 on 2019-02-20 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='showpictures',
            name='location',
            field=models.CharField(choices=[('lf', 'left'), ('ct', 'centre'), ('rg', 'right')], default='ct', max_length=2),
        ),
        migrations.AlterField(
            model_name='showpictures',
            name='picture',
            field=models.ImageField(upload_to='carousel'),
        ),
    ]
