# Generated by Django 2.1.1 on 2019-03-15 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0002_auto_20190220_2326'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShowPictures',
            new_name='ShowPicture',
        ),
    ]
