# Generated by Django 2.1.1 on 2018-10-06 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('position', models.CharField(max_length=50)),
                ('jersey_number', models.IntegerField()),
                ('nationality', models.CharField(max_length=50)),
                ('picture', models.ImageField(default='default.jpg', upload_to='player_pics')),
            ],
        ),
    ]
