# Generated by Django 2.1.1 on 2019-03-15 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_auto_20181007_0059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='position',
            field=models.CharField(choices=[('portero', 'Portero'), ('defensa', 'Defensa'), ('centrocampo', 'Centrocampista'), ('delantero', 'Delantero')], max_length=50),
        ),
    ]
